class AppLocalizations {
  AppLocalizations._();

  static const Map<String, String> defaults = {
    'nav.home': 'Home',
    'nav.recipes': 'Recipes',
    'nav.shopping': 'Shopping',
    'nav.profile': 'Profile',
    'splash.tagline': 'Cook what\'s in your fridge',
    'splash.feature.fridge': 'Fridge',
    'splash.feature.recipes': 'Recipes',
    'splash.feature.shopping': 'Shopping',
    'auth.welcomeBack': 'Welcome back',
    'auth.createAccount': 'Create your account',
    'auth.subtitleLogin': 'Sign in with your email and password.',
    'auth.subtitleRegister': 'Join FlavorCraft with your name, email and password.',
    'auth.name': 'Name',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.login': 'Sign in',
    'auth.register': 'Sign up',
    'auth.switchToRegister': 'Create an account',
    'auth.switchToLogin': 'Already have an account? Sign in',
    'auth.validation.name': 'Enter your name.',
    'auth.validation.email': 'Enter your email.',
    'auth.validation.password': 'Enter your password.',
    'auth.validation.passwordLength': 'Password must be at least 8 characters.',
    'auth.validation.passwordMatch': 'Passwords do not match.',
    'auth.error.generic': 'Something went wrong. Please try again.',
    'home.title': 'What\'s in your fridge?',
    'home.subtitle': 'Ingredients now come from your Laravel database.',
    'home.searchHint': 'Type an ingredient...',
    'home.emptyIngredients': 'No ingredients yet',
    'home.yourIngredients': 'Your Ingredients',
    'home.quickAdd': 'Quick Add',
    'home.findRecipes': 'Find Recipes',
    'home.needIngredient': 'Add at least one ingredient first.',
    'profile.title': 'Profile & Settings',
    'profile.allergies': 'Allergies',
    'profile.diet': 'Diet Preferences',
    'profile.settings': 'Settings',
    'profile.history': 'Recipe History',
    'profile.darkMode': 'Dark Mode',
    'profile.language': 'Language',
    'profile.budget': 'Budget',
    'profile.logout': 'Logout',
    'profile.recipeCount': 'Recipes',
    'profile.favoriteCount': 'Favorites',
  };

  static const Map<String, String> languageCodes = {
    'English': 'en',
    'French': 'fr',
    'Spanish': 'es',
    'Arabic': 'ar',
  };
}
